"""Release templates (phase 14): Dockerfiles, compose + Caddy (VPS) or fly.toml, runbook, smoke script, user docs."""
from __future__ import annotations

import csv
from pathlib import Path

import foundry as F

RELEASE_TEMPLATES: dict[str, str] = {}

RELEASE_TEMPLATES["apps/api/Dockerfile"] = """# api: Hono on Node 22. Runs the TypeScript sources with tsx (workspace packages export .ts); see runbook.md.
FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@9 --activate
WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json .npmrc ./
COPY apps/api/package.json apps/api/
COPY packages/db/package.json packages/db/
COPY packages/ui/package.json packages/ui/
RUN pnpm install --frozen-lockfile --filter @__APP_NAME__/api... --prod=false
COPY apps/api apps/api
COPY packages/db packages/db
RUN pnpm --filter @__APP_NAME__/db exec prisma generate
ENV NODE_ENV=production PORT=3001
EXPOSE 3001
HEALTHCHECK CMD wget -qO- http://127.0.0.1:3001/health || exit 1
CMD ["pnpm", "--filter", "@__APP_NAME__/api", "run", "start"]
"""

RELEASE_TEMPLATES["apps/web/Dockerfile"] = """# web: Next.js production server (`next start`). Standalone output is not used: pnpm symlinks break its copy step on Windows dev machines.
FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@9 --activate
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile && pnpm --filter @__APP_NAME__/web run build && pnpm prune --prod
ENV NODE_ENV=production PORT=3000
EXPOSE 3000
CMD ["pnpm", "--filter", "@__APP_NAME__/web", "run", "start"]
"""

RELEASE_TEMPLATES["compose.prod.yml"] = """# Production on one VPS (ADR 0007): Caddy terminates TLS, api + web behind it, managed or local Postgres.
services:
  db:
    image: postgres:17-alpine
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}, POSTGRES_DB: __APP_NAME__ }
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck: { test: ["CMD-SHELL", "pg_isready -U postgres"], interval: 10s, timeout: 5s, retries: 10 }
  api:
    build: { context: ., dockerfile: apps/api/Dockerfile }
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/__APP_NAME__
      DEVICE_ENROL_CODE: ${DEVICE_ENROL_CODE:?set in .env}
      WEB_ORIGIN: https://${DOMAIN:?set in .env}
      NODE_ENV: production
    depends_on: { db: { condition: service_healthy } }
    restart: unless-stopped
  web:
    build: { context: ., dockerfile: apps/web/Dockerfile }
    environment: { NEXT_PUBLIC_API_URL: https://${DOMAIN}/api-origin, NODE_ENV: production }
    restart: unless-stopped
  caddy:
    image: caddy:2-alpine
    ports: ["80:80", "443:443"]
    volumes: [./Caddyfile:/etc/caddy/Caddyfile:ro, caddy_data:/data, caddy_config:/config]
    environment: { DOMAIN: ${DOMAIN} }
    depends_on: [api, web]
    restart: unless-stopped
volumes: { pgdata: {}, caddy_data: {}, caddy_config: {} }
"""

RELEASE_TEMPLATES["Caddyfile"] = """{$DOMAIN} {
	encode zstd gzip
	handle /api/* {
		reverse_proxy api:3001
	}
	handle /health {
		reverse_proxy api:3001
	}
	handle {
		reverse_proxy web:3000
	}
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
	}
}
"""

RELEASE_TEMPLATES["fly.toml"] = """# Fly.io app (ADR 0007): one machine per organisation; Postgres via Fly Postgres or a managed provider.
app = "__APP_NAME__"
primary_region = "fra"
[build]
  dockerfile = "apps/api/Dockerfile"
[env]
  NODE_ENV = "production"
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  method = "GET"
  path = "/health"
"""

RELEASE_TEMPLATES["runbook.md"] = """# Runbook — __APP_NAME__ (deploy mode: __DEPLOY_MODE__)

Generated by `foundry.py release-skeleton`; keep it current with every release ticket.

## Start / stop

| Action | VPS (compose) | Local prod check |
|--------|---------------|------------------|
| start | `docker compose -f compose.prod.yml up -d --build` | `pnpm run build && node scripts/smoke.mjs --start` |
| stop | `docker compose -f compose.prod.yml down` | Ctrl-C / `node scripts/smoke.mjs --stop` |
| logs | `docker compose -f compose.prod.yml logs -f api web` | `.pg/dev/server.log`, api stdout (pino JSON) |
| health | `curl https://$DOMAIN/health` → `{"ok":true}` | `curl http://localhost:3101/health` |

Required env (`.env` next to compose, never committed): `POSTGRES_PASSWORD`, `DEVICE_ENROL_CODE`, `DOMAIN`, provider keys from `.foundry/wizard/*.md`.

## Backup / restore

- Nightly: `docker compose -f compose.prod.yml exec db pg_dump -U postgres -Fc __APP_NAME__ > backups/$(date +%F).dump` (cron on the VPS; keep 30 days off-box).
- Restore: `docker compose -f compose.prod.yml exec -T db pg_restore -U postgres -d __APP_NAME__ --clean < backups/<file>.dump`, then `pnpm --filter @__APP_NAME__/db exec prisma migrate deploy`.
- Verify: `SELECT count(*) FROM orders;` matches the pre-restore count from the backup log.

## Rotate device tokens

1. `POST /api/v1/devices/enrol` with a new `DEVICE_ENROL_CODE` per device (owner only); old tokens expire after 30 days or on revoke.
2. Rotate the enrol code in `.env`, `docker compose up -d api`.
3. Audit: `SELECT action, count(*) FROM audit_events WHERE action = 'device.enrolled' GROUP BY 1`.

## Reindex (code graph, dev only)

`codebase-memory-mcp` → `index_repository` on the repo root, then `python scripts/foundry.py build index --name <project>`.

## Rollback

1. `git tag` the release before deploying (`vX.Y.Z`); images are built from the tag.
2. `git checkout <previous tag> && docker compose -f compose.prod.yml up -d --build`.
3. Migrations are forward-only: a rollback that needs schema changes restores the pre-deploy backup first.

## Smoke after every deploy

`WEB_URL=https://$DOMAIN API_URL=https://$DOMAIN node scripts/smoke.mjs` → checks /health, device enrol + whoami (login), and the table map.
"""

RELEASE_TEMPLATES["scripts/smoke.mjs"] = """// Release smoke (gate release): /health, login (enrol + whoami), table map. With --start it builds nothing but boots
// the production servers from the local build (api via tsx, web via next start) on WEB_PORT/API_PORT, runs, then stops them.
import { spawn } from "node:child_process";
import { setTimeout as sleep } from "node:timers/promises";

const args = process.argv.slice(2);
const webPort = process.env.WEB_PORT ?? "3100";
const apiPort = process.env.API_PORT ?? "3101";
const webUrl = process.env.WEB_URL ?? `http://localhost:${webPort}`;
const apiUrl = process.env.API_URL ?? `http://localhost:${apiPort}`;
const enrolCode = process.env.DEVICE_ENROL_CODE ?? "release-smoke-code";
const branch = process.env.SMOKE_BRANCH_ID ?? "11111111-1111-4111-8111-111111111111";
const procs = [];

function start(cmd, argv, env) {
  const p = spawn(cmd, argv, { env: { ...process.env, ...env }, shell: process.platform === "win32", stdio: ["ignore", "pipe", "pipe"] });
  p.stdout.on("data", () => {});
  p.stderr.on("data", () => {});
  procs.push(p);
}
async function waitFor(url, ms = 120_000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    try { const r = await fetch(url); if (r.ok) return; } catch { /* not up yet */ }
    await sleep(1000);
  }
  throw new Error(`timeout waiting for ${url}`);
}
const checks = [];
const check = (name, ok, detail = "") => { checks.push({ name, ok, detail }); console.log(`${ok ? "ok  " : "FAIL"} ${name} ${detail}`); };

try {
  if (args.includes("--start")) {
    start("pnpm", ["--filter", "@__APP_NAME__/api", "exec", "tsx", "src/index.ts"], { PORT: apiPort, API_PORT: apiPort, DEVICE_ENROL_CODE: enrolCode, WEB_ORIGIN: webUrl, NODE_ENV: "production" });
    start("pnpm", ["--filter", "@__APP_NAME__/web", "exec", "next", "start", "-p", webPort], { PORT: webPort, NEXT_PUBLIC_API_URL: apiUrl, NODE_ENV: "production" });
    await waitFor(`${apiUrl}/health`);
    await waitFor(`${webUrl}/`);
  }
  const h = await fetch(`${apiUrl}/health`);
  check("health", h.ok && (await h.json()).ok === true);
  const enrol = await fetch(`${apiUrl}/api/v1/devices/enrol`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `smoke-${Date.now()}` }, body: JSON.stringify({ branch_id: branch, name: "smoke", enrol_code: enrolCode }) });
  check("login: device enrol", enrol.status === 201, String(enrol.status));
  const token = enrol.ok ? (await enrol.json()).token : "";
  const who = await fetch(`${apiUrl}/api/v1/whoami`, { headers: { authorization: `Bearer ${token}` } });
  check("login: whoami", who.ok && (await who.json()).branch_id === branch);
  const tm = await fetch(`${webUrl}/table-map`);
  const html = await tm.text();
  check("table map renders", tm.ok && /table-map|Tables|الطاولات/.test(html));
  const home = await fetch(`${webUrl}/`);
  check("home renders", home.ok);
} catch (e) {
  check("smoke", false, e instanceof Error ? e.message : String(e));
} finally {
  for (const p of procs) {
    try {
      if (process.platform === "win32") spawn("taskkill", ["/pid", String(p.pid), "/T", "/F"]);
      else p.kill("SIGTERM");
    } catch { /* already gone */ }
  }
}
const failed = checks.filter((c) => !c.ok);
console.log(`smoke: ${checks.length - failed.length}/${checks.length} passed`);
process.exit(failed.length ? 1 : 0);
"""


def _screens(project: Path) -> list[dict]:
    out = []
    sd = project / ".foundry" / "screens"
    if not sd.exists():
        return out
    for p in sorted(sd.glob("*.md")):
        fm, _, body = F.split_frontmatter(p.read_text(encoding="utf-8"))
        d = F.parse_yaml(fm)
        purpose = body.split("## Purpose", 1)[1].split("\n## ", 1)[0].strip().splitlines() if "## Purpose" in body else [""]
        states = {}
        sect = body.split("## States", 1)[1].split("\n## ", 1)[0] if "## States" in body else ""
        for line in sect.splitlines():
            if line.startswith("|") and not line.startswith("| State") and not line.startswith("|---"):
                cells = [c.strip() for c in line.strip("|").split("|")]
                if len(cells) >= 3:
                    states[cells[0]] = (cells[1].strip('"'), cells[2].strip('"'))
        out.append({"id": d.get("id", p.stem), "route": d.get("route", "/" + p.stem), "personas": d.get("personas") or [], "purpose": purpose[0] if purpose else "", "states": states})
    return out


def _copy(root: Path) -> dict[str, dict]:
    p = root / "data" / "copy.csv"
    out = {}
    if p.exists():
        with p.open(encoding="utf-8", newline="") as fh:
            for r in csv.DictReader(fh):
                out[r["id"]] = r
    return out


def user_docs(project: Path, root: Path) -> dict[str, str]:
    screens = _screens(project)
    copy = _copy(root)
    act = lambda k, lang: copy.get(f"action.{k}", {}).get(lang, k)
    cashier = [s for s in screens if "cashier" in s["personas"] or "waiter" in s["personas"]]
    manager = [s for s in screens if "manager" in s["personas"] or "owner" in s["personas"]]
    en = ["# Cashier quick start", "", "One screen per task. The device keeps working offline; orders sync when the connection returns.", ""]
    for s in cashier:
        en += [f"## {s['id'].replace('-', ' ').title()} (`{s['route']}`)", "", s["purpose"] or "", ""]
        if s["states"]:
            en += ["| When you see | It means |", "|---|---|"] + [f"| {v[0]} | {k} |" for k, v in s["states"].items() if v[0]] + [""]
    en += ["## Buttons you will use", "", ", ".join(act(k, "en") for k in ("add-item", "send-to-kitchen", "pay", "cash", "card", "print-bill", "split-bill", "open-shift", "close-shift")), ""]
    ar = ["# دليل الكاشير السريع", "", "شاشة واحدة لكل مهمة. يستمر الجهاز بالعمل دون اتصال، وتتم مزامنة الطلبات عند عودة الاتصال.", ""]
    for s in cashier:
        ar += [f"## {s['id']} (`{s['route']}`)", ""]
        if s["states"]:
            ar += ["| عندما ترى | المعنى |", "|---|---|"] + [f"| {v[1]} | {k} |" for k, v in s["states"].items() if v[1]] + [""]
    ar += ["## الأزرار", "", "، ".join(act(k, "ar") for k in ("add-item", "send-to-kitchen", "pay", "cash", "card", "print-bill", "split-bill", "open-shift", "close-shift")), ""]
    mg = ["# Manager guide", "", "Manager and owner screens, plus the approvals cashiers will ask you for (manager PIN).", ""]
    for s in manager:
        mg += [f"## {s['id'].replace('-', ' ').title()} (`{s['route']}`)", "", s["purpose"] or "", ""]
        locked = s["states"].get("locked")
        if locked and locked[0]:
            mg += [f"Approval prompt: *{locked[0]}*", ""]
    mg += ["## Daily routine", "", "1. Open shift with the float count.", "2. Approve voids, comps, discounts and refunds with your PIN (every approval is audited with your id).", "3. Close shift: count cash, review variance, print the Z report.", "4. End of day: check sync status shows zero pending events before closing the terminals.", ""]
    return {"user-docs/cashier-quick-start.en.md": "\n".join(en) + "\n", "user-docs/cashier-quick-start.ar.md": "\n".join(ar) + "\n", "user-docs/manager-guide.en.md": "\n".join(mg) + "\n"}
